
uv run appworld run ACE_offline_with_GT_bullet_analyzer_FMB_improved_evaluation
uv run appworld evaluate ACE_offline_with_GT_bullet_analyzer_FMB_improved_evaluation test_normal

uv run appworld run ACE_offline_with_GT_bullet_analyzer_FMB_improved_evaluation_challenge
uv run appworld evaluate ACE_offline_with_GT_bullet_analyzer_FMB_improved_evaluation_challenge test_challenge

uv run appworld run ACE_offline_with_GT_curator_operations_RAE
uv run appworld run ACE_offline_with_GT_curator_operations_RAE_evaluation
uv run appworld evaluate ACE_offline_with_GT_curator_operations_RAE_evaluation test_normal

uv run appworld run ACE_offline_with_GT_curator_operations_RAE_evaluation_challenge
uv run appworld evaluate ACE_offline_with_GT_curator_operations_RAE_evaluation_challenge test_challenge